# Generated by Django 5.0.7 on 2024-07-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamerandom_gamesearch_gamesolo_delete_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerandom',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamerandom',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamerandom',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesearch',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesearch',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesearch',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesolo',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesolo',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesolo',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
    ]
