# Generated by Django 5.0.7 on 2024-07-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamerandom_game_mode_gamesearch_game_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerandom',
            name='player2_answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamerandom',
            name='player2_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesearch',
            name='player2_answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesearch',
            name='player2_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesolo',
            name='player2_answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesolo',
            name='player2_questions',
            field=models.JSONField(default=list),
        ),
    ]
