# Generated by Django 5.0.7 on 2024-08-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gamerandom_player2_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerandom',
            name='questions_answered_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerandom',
            name='questions_answered_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerandom',
            name='score_player2',
            field=models.IntegerField(default=0),
        ),
    ]
