# Generated by Django 5.0.7 on 2024-08-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamerandom_questions_answered_player1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerandom',
            name='score_player2',
        ),
        migrations.RemoveField(
            model_name='gamesearch',
            name='questions_answered',
        ),
        migrations.RemoveField(
            model_name='gamesolo',
            name='questions_answered',
        ),
        migrations.AddField(
            model_name='gamesearch',
            name='questions_answered_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesearch',
            name='questions_answered_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesolo',
            name='questions_answered_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesolo',
            name='questions_answered_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamerandom',
            name='player2_answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gamerandom',
            name='player2_questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gamesearch',
            name='player2_answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gamesearch',
            name='player2_questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gamesolo',
            name='player2_answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gamesolo',
            name='player2_questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
