# Generated by Django 5.0.7 on 2024-08-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_gamerandom_score_player2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerandom',
            name='questions_answered',
        ),
        migrations.AlterField(
            model_name='gamerandom',
            name='questions_answered_player2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gamesearch',
            name='questions_answered_player2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gamesolo',
            name='questions_answered_player2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
