# Generated by Django 5.0.7 on 2024-08-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_gamerandom_questions_answered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerandom',
            name='player2_answers',
        ),
        migrations.RemoveField(
            model_name='gamerandom',
            name='player2_questions',
        ),
        migrations.RemoveField(
            model_name='gamesearch',
            name='player2_answers',
        ),
        migrations.RemoveField(
            model_name='gamesearch',
            name='player2_questions',
        ),
        migrations.RemoveField(
            model_name='gamesolo',
            name='player2_answers',
        ),
        migrations.RemoveField(
            model_name='gamesolo',
            name='player2_questions',
        ),
        migrations.AddField(
            model_name='gamerandom',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamerandom',
            name='questions_answered_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesearch',
            name='questions_answered_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesolo',
            name='questions_answered_player2',
            field=models.IntegerField(default=0),
        ),
    ]
