# Generated by Django 5.0.7 on 2024-08-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_gamerandom_player2_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerandom',
            name='score_player2',
            field=models.IntegerField(default=0),
        ),
    ]
