# Generated by Django 5.0.7 on 2024-08-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gamerandom_score_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerandom',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='gamesearch',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='gamesolo',
            name='answers',
        ),
    ]
