# Generated by Django 5.0.7 on 2024-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_gamerandom_answers_remove_gamesearch_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerandom',
            name='points_updated',
            field=models.BooleanField(default=False),
        ),
    ]
